# Generated by Django 5.0.1 on 2024-01-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='desc',
            field=models.TextField( max_length=10000),
        ),
    ]
