# Generated by Django 5.0.1 on 2024-01-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='desc',
            field=models.TextField(max_length=10000),
        ),
    ]
