# Generated by Django 5.0.1 on 2024-01-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='descp',
            field=models.TextField(default='Tell you though about it', max_length=1000000),
        ),
    ]
